In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

num_records = 100  # Number of simulated logs

# Possible fitness activities
activities = ["Walk", "Run", "Cycling", "Yoga", "Strength Training", "Swimming"]

# Empty list to hold all records
data = []

for _ in range(num_records):
    activity = np.random.choice(activities)
    duration = np.random.randint(10, 90)  # 10 to 90 minutes
    steps = np.random.randint(2000, 15000) if activity in ["Walk", "Run"] else 0
    heart_rate = np.random.randint(90, 160) if activity in ["Run", "Cycling", "Strength Training"] else np.random.randint(70, 120)
    calories = round(duration * (5 + np.random.random() * 7), 1)  # basic formula

    record = {
        "timestamp": datetime.now() - timedelta(minutes=np.random.randint(0, 1440)),
        "user_id": f"USER{np.random.randint(1000, 9999)}",
        "activity_type": activity,
        "duration_minutes": duration,
        "steps": steps,
        "calories_burned": calories,
        "avg_heart_rate": heart_rate
    }

    data.append(record)

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to files
df.to_csv("fitness_milestone_data.csv", index=False)
df.to_json("fitness_milestone_data.json", orient="records")

# Show preview
df.head()

,timestamp,user_id,activity_type,duration_minutes,steps,calories_burned,avg_heart_rate
0,2025-05-30 12:36:38.400715,USER8290,Strength Training,19,0,99.9,125
1,2025-05-30 13:07:38.400715,USER6338,Walk,22,5940,126.5,109
2,2025-05-30 22:24:38.400715,USER8347,Yoga,64,0,366.8,81
3,2025-05-30 04:58:38.400715,USER6468,Walk,70,6465,682.2,87
4,2025-05-30 23:16:38.401722,USER9082,Walk,82,11450,576.5,116